import pathlib
import random


script_folder = pathlib.Path(__file__).resolve().parent
project_folder = script_folder.parent
output_folder = (
    project_folder
    / "quartus_bch_product_encoder"
    / "simulation"
    / "modelsim"
    / "testfiles"
)

output_path = output_folder / "productTestData.txt"

# Generate random test data for the product encoder. Each row is a 239-bit binary string.
def generate_product_testdata(blocks=1, seed=42):
    random_generator = random.Random(seed) # Use a local random generator instance with a fixed seed for reproducibility.
    output_folder.mkdir(parents=True, exist_ok=True) # Ensure the output directory exists.

    # Earlier version would recreate the file when it was imported in the main testscript
    # Therefore this version fixes this by using "with open", so that the file is only created when this script is run.
    with open(output_path, "w", encoding="ascii") as output_file:
        output_file.write(
            "-- Random product test data generated by generate_product_testdata.py"
        )

        # Generate random blocks of data.
        for _ in range(blocks * 239):
            data_row = format(random_generator.getrandbits(239), "0239b")
            output_file.write("\n" + data_row)

    return output_path


if __name__ == "__main__":
    generate_product_testdata(blocks=10)