import pathlib

def lfsr_remainder(message_bits):
    """
    Return the 16-bit BCH remainder for one 239-bit message string.
    The 16 trailing zero bits required for systematic encoding are added here.
    This is different from the other version, which expected the input to already have the 16 zeroes appended.
    """
    genpoly = 0b0110111101100011 # Generator polynomial without the leading 1-bit (same as is done in VHDL, as the first bit is handled by the outgoing_bit logic)
    parity_bits = 16

    remainder = 0
    remainder_mask = (1 << parity_bits) - 1 # Mask to force the remainder to stay within 16 bits

    for bit_char in message_bits + ("0" * parity_bits): # go through each bit in the message and append 16 zeroes for the systematic encoding
        outgoing_bit = (remainder >> (parity_bits - 1)) # Get the MSB of the remainder before shifting it (the leftmost bit)
        remainder = ((remainder << 1) | int(bit_char)) & remainder_mask # Shift left and add the new bit, then mask to 16 bits

        # If the outgoing bit is 1, we need to XOR with the generator polynomial
        # genpoly contains the lower 16 coefficients of the generator polynomial.
        # The leading x^16 term is handled through outgoing_bit and removed by remainder_mask.
        if outgoing_bit == 1: 
            remainder ^= genpoly

    return remainder

# Create 1 codeword from 239 bits in the same format that the VHDL encoder does it.
def encode_component(message_bits):
    remainder = lfsr_remainder(message_bits)
    remainder_bits = f"{remainder:016b}"

    parity_bit = (message_bits.count("1") + remainder_bits.count("1")) % 2

    return message_bits + remainder_bits + str(parity_bit)

# Verify that the output of the Python encoder matches the VHDL encoder for a given message and codeword.
def verify_component_encoder(message_bits, vhdl_codeword):
    python_codeword = encode_component(message_bits)
    return python_codeword == vhdl_codeword


# Encode a product block of 239 rows of 239 bits, and return the resulting 256 codewords.
def encode_product_block(data_rows):
    if len(data_rows) != 239:
        raise ValueError("A product block must contain exactly 239 input rows.")

    row_codewords = []

    # First, encode each row as a component codeword.
    for row_bits in data_rows:
        row_codewords.append(encode_component(row_bits))

    product_codewords = []

    # Then we construct a column from 1 bit from each of the 239 row codewords
    # And encode it as a codeword too, to get the final product codewords.
    for column_index in range(256):
        column_bits = ""

        for row_codeword in row_codewords:
            column_bits += row_codeword[column_index]

        product_codewords.append(encode_component(column_bits))

    return product_codewords # return array of 256 codewords, each 256 bits long.


# Find the testfiles folder from this script's location, so it works no matter where the script is run from.
script_folder = pathlib.Path(__file__).resolve().parent
project_folder = script_folder.parent

testfiles_folder = (
    project_folder
    / "quartus_bch_product_encoder"
    / "simulation"
    / "modelsim"
    / "testfiles"
)

input_path = testfiles_folder / "productTestData.txt" # Generated by generate_product_testdata.py, contains 2390 lines of 239 bits (10 product blocks).
output_path = testfiles_folder / "productEncoderOutput.txt" # Generated by running the VHDL testbench, contains 2560 lines of 256 bits (10 product blocks with 256 codewords each).


def verify_product_encoder_output():
    input_rows = []

    with open(input_path, "r", encoding="ascii") as input_file:
        input_file.readline()  # Skip the header.
        for line in input_file:
            input_rows.append(line.strip())

    vhdl_codewords = []
    with open(output_path, "r", encoding="ascii") as output_file:
        for line in output_file:
            vhdl_codewords.append(line.strip())

    if len(input_rows) % 239 != 0:
        raise ValueError("The input file does not contain a whole number of product blocks.")

    expected_codewords = []

    for first_row in range(0, len(input_rows), 239):
        data_rows = input_rows[first_row:first_row + 239]
        expected_codewords.extend(encode_product_block(data_rows))

    if len(vhdl_codewords) != len(expected_codewords):
        print(f"FAIL: expected {len(expected_codewords)} output codewords, "
              f"but ModelSim wrote {len(vhdl_codewords)}.")
        return False

    incorrect_codewords = 0

    for index, (expected_codeword, vhdl_codeword) in enumerate(
        zip(expected_codewords, vhdl_codewords),
        start=1
    ):
        if expected_codeword != vhdl_codeword:
            incorrect_codewords += 1
            print(f"Mismatch in output codeword {index}.")

    product_blocks = len(input_rows) // 239

    print(f"Tested {product_blocks} product block(s), "
          f"{len(expected_codewords)} output codewords.")

    if incorrect_codewords == 0:
        print("PASS: Python reference and VHDL product encoder match.")
        return True

    print(f"FAIL: {incorrect_codewords} codeword(s) differ.")
    return False

if __name__ == "__main__":
    verify_product_encoder_output()