import random
import pathlib

endOfLine = "\n"
output_folder = pathlib.Path(r"C:\Users\Gustav\OneDrive - Danmarks Tekniske Universitet\Desktop\DTU\Fagprojekt (34299)\python sim files")
file  = open(output_folder / "productTestData.txt", "w")

def randomProductData(blocks = 1):
    # Reproduce this testdata
    random.seed(42)
    # Header comment.
    file.write("-- This is randomly generated test data, generated by the 'generate_testdata.py' script") 
    total_lines = blocks*239
    for i in range(total_lines):
        # use [2:] slicing to remove "0b" prefix
        # use zfill to ensure the binary string is exactly 239 bits long (padding leading zeroes if neccesary)
        file.write(endOfLine + bin(random.getrandbits(239))[2:].zfill(239))


randomProductData(blocks = 10) 
file.close()