import random
import pathlib

endOfLine = "\n"
random.seed = 42
maxErrors = 3

fileR  = open(pathlib.Path("sim","TestFiles","encoderOutput.txt"), "r")
fileW  = open(pathlib.Path("sim","TestFiles","codes_with_errors.txt"), "w")
fileW.write("This is codewords, with errors added generated by 'add_errors_to_data.py'. Format is: error count, codeword with error (in hex)")
#line = fileR.readline()
print("found files")
line = fileR.readline().strip()
while line != "":
    codeword = int(line,2)
    errorPos = []
    for i in range(random.randint(0,maxErrors)):
        while True:
            errorLocation = random.randint(0,255)
            if errorPos.count(errorLocation)== 0 :
                errorPos.append(errorLocation)
                codeword = codeword ^ (2**errorLocation)
                break
    fileW.write(endOfLine+str(len(errorPos))+ " "+hex(codeword)[2:].zfill(64))
    line = fileR.readline().strip()


fileR.close()
fileW.close()