import random
import pathlib

endOfLine = "\n"
random.seed = 42
maxErrors = 1
addErrorCount = False

fileR  = open(pathlib.Path("sim","TestFiles","encoderOutput.txt"), "r")
fileW  = open(pathlib.Path("sim","TestFiles","codes_with_errors.txt"), "w")
#fileW.write("This is codewords, with errors added generated by 'add_errors_to_data.py'. Format is: error count, codeword with error (in hex)")
#line = fileR.readline()
print("found files")
def randomErrors():
    line = fileR.readline().strip()
    while line != "":
        codeword = int(line,2)
        errorPos = []
        for i in range(random.randint(0,maxErrors)):
            while True:
                errorLocation = random.randint(0,255)
                if errorPos.count(errorLocation)== 0 :
                    errorPos.append(errorLocation)
                    codeword = codeword ^ (2**errorLocation)
                    break
        if addErrorCount:
            fileW.write(endOfLine+str(len(errorPos))+ " "+hex(codeword)[2:].zfill(64))
        else:
            fileW.write(endOfLine+hex(codeword)[2:].zfill(64))
        line = fileR.readline().strip()
        
def systematic1error():
    print("adding diagonal error pattern")
    #fileW.write("diagonal error pattern")
    line = fileR.readline().strip()
    i = 0
    while line != "":
        codeword = int(line,2)
        codeword = codeword ^ 2**(i+1)
        
        if addErrorCount:
            fileW.write(endOfLine+str(1)+" "+hex(codeword)[2:].zfill(64))
        else:
            fileW.write(endOfLine+hex(codeword)[2:].zfill(64))
        i += 1
        line = fileR.readline().strip()
    
systematic1error()

fileR.close()
fileW.close()
# TODO
# make file with error positions and count