import random
import pathlib

endOfLine = "\n"
random.seed = 42
file  = open(pathlib.Path("sim","TestFiles","testData.txt"), "w")

file.write("This is randomly generated test data, generated by the 'generate_testdata.py' script")

for i in range(256):
    file.write(endOfLine + bin(random.getrandbits(239))[2:].zfill(239))
    
file.close()