LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE std.textio.ALL;
USE ieee.std_logic_textio.ALL;



-- This TB is reusing some of the stuff from the product encoder TB.
-- Some comments are therefore left out, and further explanations are available in that file.
-- Explanations of the product decoder is available in it's file too, and will not be mentioned that much here.
ENTITY product_decoder_file_tb IS
    GENERIC (
        ITERATIONS : INTEGER := 3 -- We must add "ITERATIONS" in this TB's entity, because we want to manipulate it from the python test script.
    );
END ENTITY product_decoder_file_tb;

ARCHITECTURE Behavioral OF product_decoder_file_tb IS

-- DUT is the product decoder.
-- The logic is explained in its file.
COMPONENT product_decoder
    GENERIC (
        M          : INTEGER := 8;
        T          : INTEGER := 2;
        ITERATIONS : INTEGER := 3
    );
    PORT (
        clk            : IN STD_LOGIC;
        reset          : IN STD_LOGIC;

        column_valid   : IN STD_LOGIC;
        column_in      : IN STD_LOGIC_VECTOR(255 DOWNTO 0);
        column_ready   : OUT STD_LOGIC;

        codeword_valid : OUT STD_LOGIC;
        codeword_out   : OUT STD_LOGIC_VECTOR(255 DOWNTO 0);
        block_done     : OUT STD_LOGIC
    );
END COMPONENT;

    -- Signals connecting the testbench to the decoder DUT.
	 -- The main difference from the encoder, is that we now use "column" instead of "row" for the 3 in/valid/ready signals.
	 -- Most of the other logic is identical.
	SIGNAL clk            : STD_LOGIC := '0';
	SIGNAL reset          : STD_LOGIC := '0';

	SIGNAL column_in      : STD_LOGIC_VECTOR(255 DOWNTO 0) := (OTHERS => '0');
	SIGNAL column_valid   : STD_LOGIC := '0';
	SIGNAL column_ready   : STD_LOGIC;

	SIGNAL codeword_out   : STD_LOGIC_VECTOR(255 DOWNTO 0);
	SIGNAL codeword_valid : STD_LOGIC;
	SIGNAL block_done     : STD_LOGIC;

   file input_file : TEXT open READ_MODE is "testfiles/productCodewordsWithErrors.txt"; -- This is generated by python scripts
   file output_file : TEXT open WRITE_MODE is "testfiles/productDecoderOutput.txt"; -- This is made by this TB.

   constant CLK_PERIOD : TIME := 20 ns;

BEGIN
   -- Instantiate the product decoder DUT.
dut : product_decoder
    GENERIC MAP (
        M          => 8,
        T          => 2,
        ITERATIONS => ITERATIONS
    )
    PORT MAP (
        clk            => clk,
        reset          => reset,

        column_valid   => column_valid,
        column_in      => column_in,
        column_ready   => column_ready,

        codeword_valid => codeword_valid,
        codeword_out   => codeword_out,
        block_done     => block_done
    );

    -- Clock generation is the same for this version too.
    clk_process : PROCESS
    BEGIN
        WHILE true LOOP
            clk <= '0';
            WAIT FOR CLK_PERIOD / 2;
            clk <= '1';
            WAIT FOR CLK_PERIOD / 2;
        END LOOP;
    END PROCESS;

   -- Read noisy column codewords from Python and send them to the decoder.
	-- This is mostly the same as the encoder TB
stimulus_process : PROCESS
    VARIABLE line_in  : line;
    VARIABLE column_v : STD_LOGIC_VECTOR(255 DOWNTO 0);
BEGIN
    reset <= '1';
    column_valid <= '0';

    WAIT FOR CLK_PERIOD * 2;
    reset <= '0';
    WAIT FOR CLK_PERIOD * 2.5;

    WHILE NOT endfile(input_file) LOOP
        readline(input_file, line_in);
        read(line_in, column_v);

        column_in <= column_v;
        column_valid <= '1';

        -- Keep this column stable until the decoder accepts it.
        LOOP
            WAIT UNTIL RISING_EDGE(clk);
            EXIT WHEN column_ready = '1';
        END LOOP;
    END LOOP;

    column_valid <= '0';
    WAIT;
END PROCESS;

 -- Write each valid decoded codeword to the output file.
	capture_output : PROCESS
		 VARIABLE output_line : line;
	BEGIN
		 WAIT UNTIL RISING_EDGE(clk);

		 IF codeword_valid = '1' THEN
			  write(output_line, codeword_out);
			  writeline(output_file, output_line);
		 END IF;
END PROCESS;
END ARCHITECTURE Behavioral;