import random
import pathlib

endOfLine = "\n"
random.seed = 42
maxErrors = 2
minErrors = 2
addErrorCount = False

fileR  = open(pathlib.Path("sim","TestFiles","encoderOutput.txt"), "r")
fileW  = open(pathlib.Path("sim","TestFiles","codes_with_errors.txt"), "w")
fileErrorPos = open(pathlib.Path("sim","TestFiles","error_pos.txt"), "w")
#fileW.write("This is codewords, with errors added generated by 'add_errors_to_data.py'. Format is: error count, codeword with error (in hex)")
line = fileR.readline()
print("found files")

def write_it_down(codeword, error_list):
    fileErrorPos.write(endOfLine)
    for e in error_list:
        fileErrorPos.write(hex(e)[2:].zfill(2) + " ")
        codeword = codeword ^ (1<<e)
    fileW.write(endOfLine+hex(codeword)[2:].zfill(64))
    

def randomErrors():
    line = fileR.readline().strip()
    while line != "":
        codeword = int(line,2)
        errorPos = []
        for i in range(random.randint(minErrors,maxErrors)):
            while True:
                errorLocation = random.randint(0,255)
                if errorPos.count(errorLocation)== 0 :
                    errorPos.append(errorLocation)
                    break
        write_it_down(codeword, errorPos)
        line = fileR.readline().strip()
        
def systematicError():
    print("adding diagonal error pattern")
    #fileW.write("diagonal error pattern")
    line = fileR.readline().strip()
    i = 0
    while line != "":
        codeword = int(line,2)
        epos = [i+1, 1] #+4 => 2 lines wrong
        epos[0] = epos[0]%256
        epos[1] = epos[1]%256
        
        write_it_down(codeword, epos)
        i += 1
        line = fileR.readline().strip()
    
def allTheCorrectableErrors():
    codeword = int(fileR.readline().strip(), 2)
    
    #the no error pattern 
    write_it_down(codeword, [])
    
    #all the error patterns with a single error
    for i in range(256):
        write_it_down(codeword, [i])
    
    #all the unique error patterns with 2 errors
    for i in range(256):
        for j in range(i+1, 256):
            write_it_down(codeword, [i,j])
            
allTheCorrectableErrors()

print("done")
fileR.close()
fileW.close()
fileErrorPos.close()