import random
import pathlib

endOfLine = "\n"

file  = open(pathlib.Path("sim","TestFiles","testData.txt"), "w")

def randomData(lines = 4*239):
    random.seed = 42
    # file.write("-- This is randomly generated test data, generated by the 'generate_testdata.py' script")

    for i in range(lines):
        file.write(endOfLine + bin(random.getrandbits(239))[2:].zfill(239))

def piData():
    file.write("-- This is the first 72 digits of pi in binary, generated by the 'generate_testdata.py' script")
    first_digits_of_pi= 314159265358979323846264338327950288419716939937510582097494459230781640
    
    file.write(endOfLine + bin(first_digits_of_pi)[2:].zfill(239))

randomData() 
file.close()